-keep class com.liskovsoft.leanbackassistant.channels.RunOnInstallReceiver { *; }
-keep class androidx.core.view.ViewCompat { *; }
-keep class androidx.work.impl.WorkManagerInitializer { *; }
-keep class **$r8$backportedMethods$** { *; }
-keep class kotlin.text.StringsKt__StringsJVMKt { *; }