-keep class com.liskovsoft.smartyoutubetv2.common.app.presenters.ChannelUploadsPresenter { *; }
-keep class com.liskovsoft.leanbackassistant.channels.RunOnInstallReceiver { *; }
-keep class androidx.core.view.ViewCompat { *; }
-keep class androidx.work.impl.WorkManagerInitializer { *; }
-keep class **$r8$backportedMethods$** { *; }
-keep class kotlin.text.StringsKt__StringsJVMKt { *; }
-keep class kotlin.ranges.RangesKt___RangesKt { *; }
-keep class kotlin.jvm.functions.Function1 { *; }
#-keep class kotlin.collections.builders.* { *; }
#-keep class androidx.room.** { *; }